version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/server_py"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
