-- Seed default coding questions
INSERT INTO coding_questions (
  title,
  description,
  difficulty,
  starter_code,
  test_cases,
  sample_cases,
  hidden_cases,
  input_format,
  output_format,
  constraints_text,
  topic_tags,
  accepted_languages,
  marks
) VALUES
('Two Sum', 'Given an array of integers and a target, print the indices of two numbers that add up to the target. Print the smaller index first.', 'easy', 'n = int(input())\narr = list(map(int, input().split()))\ntarget = int(input())\n# write your code here', '[{"input":"4\n2 7 11 15\n9","expected_output":"0 1"},{"input":"5\n1 3 4 6 8\n10","expected_output":"2 3"}]', '[{"input":"4\n2 7 11 15\n9","expected_output":"0 1"}]', '[{"input":"6\n5 1 9 2 8 4\n13","expected_output":"0 4"}]', 'n, array elements, target', 'Two zero-based indices', '2 <= n <= 100000', '["array","hashing"]', '["python","java","cpp","javascript"]', 10),
('Reverse Words', 'Given a sentence, reverse the order of words while keeping each word unchanged.', 'easy', 's = input().strip()\n# write your code here', '[{"input":"campus hiring platform","expected_output":"platform hiring campus"},{"input":"hello world","expected_output":"world hello"}]', '[{"input":"campus hiring platform","expected_output":"platform hiring campus"}]', '[{"input":"one two three four","expected_output":"four three two one"}]', 'A single line string', 'Words in reversed order', '1 <= length <= 10000', '["string"]', '["python","java","cpp","javascript"]', 10),
('Valid Parentheses', 'Check whether a string containing brackets (), {}, [] is balanced. Print YES or NO.', 'easy', 's = input().strip()\n# write your code here', '[{"input":"({[]})","expected_output":"YES"},{"input":"([)]","expected_output":"NO"}]', '[{"input":"({[]})","expected_output":"YES"}]', '[{"input":"((()))[]{}","expected_output":"YES"}]', 'Bracket string', 'YES or NO', '1 <= length <= 100000', '["stack","string"]', '["python","java","cpp","javascript"]', 10),
('Maximum Subarray Sum', 'Find the maximum possible sum of a contiguous subarray.', 'easy', 'n = int(input())\narr = list(map(int, input().split()))\n# write your code here', '[{"input":"5\n-2 1 -3 4 -1","expected_output":"4"},{"input":"4\n1 2 3 4","expected_output":"10"}]', '[{"input":"5\n-2 1 -3 4 -1","expected_output":"4"}]', '[{"input":"6\n-5 -1 -8 -2 -3 -4","expected_output":"-1"}]', 'n and array', 'Maximum sum', '1 <= n <= 100000', '["array","dynamic-programming"]', '["python","java","cpp","javascript"]', 10),
('Count Frequencies', 'Print each distinct integer and its frequency in first-occurrence order.', 'easy', 'n = int(input())\narr = list(map(int, input().split()))\n# write your code here', '[{"input":"7\n4 5 4 6 5 4 7","expected_output":"4 3\n5 2\n6 1\n7 1"}]', '[{"input":"7\n4 5 4 6 5 4 7","expected_output":"4 3\n5 2\n6 1\n7 1"}]', '[{"input":"5\n1 1 1 1 1","expected_output":"1 5"}]', 'n and array', 'value frequency per line', '1 <= n <= 100000', '["hashing","array"]', '["python","java","cpp","javascript"]', 10),
('Binary Search', 'Given a sorted array and key, print the index of the key or -1 if absent.', 'easy', 'n = int(input())\narr = list(map(int, input().split()))\nkey = int(input())\n# write your code here', '[{"input":"5\n1 3 5 7 9\n7","expected_output":"3"},{"input":"4\n2 4 6 8\n5","expected_output":"-1"}]', '[{"input":"5\n1 3 5 7 9\n7","expected_output":"3"}]', '[{"input":"6\n10 20 30 40 50 60\n10","expected_output":"0"}]', 'n, sorted array, key', 'Index or -1', '1 <= n <= 100000', '["binary-search","array"]', '["python","java","cpp","javascript"]', 10),
('Merge Intervals Count', 'Given intervals, merge overlapping intervals and print the number of intervals after merging.', 'medium', 'n = int(input())\nintervals = [tuple(map(int, input().split())) for _ in range(n)]\n# write your code here', '[{"input":"4\n1 3\n2 6\n8 10\n15 18","expected_output":"3"},{"input":"2\n1 4\n4 5","expected_output":"1"}]', '[{"input":"4\n1 3\n2 6\n8 10\n15 18","expected_output":"3"}]', '[{"input":"3\n1 2\n3 4\n5 6","expected_output":"3"}]', 'n followed by intervals', 'Merged interval count', '1 <= n <= 100000', '["sorting","intervals"]', '["python","java","cpp","javascript"]', 15),
('Longest Unique Substring', 'Print the length of the longest substring without repeating characters.', 'medium', 's = input().strip()\n# write your code here', '[{"input":"abcabcbb","expected_output":"3"},{"input":"bbbbb","expected_output":"1"}]', '[{"input":"abcabcbb","expected_output":"3"}]', '[{"input":"pwwkew","expected_output":"3"}]', 'String s', 'Integer length', '1 <= length <= 100000', '["sliding-window","string"]', '["python","java","cpp","javascript"]', 15),
('Rotate Array', 'Rotate an array to the right by k positions and print the result.', 'medium', 'n, k = map(int, input().split())\narr = list(map(int, input().split()))\n# write your code here', '[{"input":"5 2\n1 2 3 4 5","expected_output":"4 5 1 2 3"},{"input":"3 4\n1 2 3","expected_output":"3 1 2"}]', '[{"input":"5 2\n1 2 3 4 5","expected_output":"4 5 1 2 3"}]', '[{"input":"1 100\n9","expected_output":"9"}]', 'n k and array', 'Rotated array', '1 <= n <= 100000', '["array"]', '["python","java","cpp","javascript"]', 15),
('Matrix Diagonal Sum', 'Given an n x n matrix, print the sum of primary and secondary diagonals, counting center once.', 'medium', 'n = int(input())\nmat = [list(map(int, input().split())) for _ in range(n)]\n# write your code here', '[{"input":"3\n1 2 3\n4 5 6\n7 8 9","expected_output":"25"},{"input":"2\n1 2\n3 4","expected_output":"10"}]', '[{"input":"3\n1 2 3\n4 5 6\n7 8 9","expected_output":"25"}]', '[{"input":"1\n7","expected_output":"7"}]', 'n and matrix rows', 'Diagonal sum', '1 <= n <= 500', '["matrix"]', '["python","java","cpp","javascript"]', 15),
('First Non-Repeating Character', 'Print the first character that appears exactly once, or -1 if none exists.', 'medium', 's = input().strip()\n# write your code here', '[{"input":"swiss","expected_output":"w"},{"input":"aabb","expected_output":"-1"}]', '[{"input":"swiss","expected_output":"w"}]', '[{"input":"recruiter","expected_output":"c"}]', 'String s', 'Character or -1', '1 <= length <= 100000', '["hashing","string"]', '["python","java","cpp","javascript"]', 15),
('Minimum Platforms', 'Given arrival and departure times, print the minimum number of platforms required.', 'medium', 'n = int(input())\narr = list(map(int, input().split()))\ndep = list(map(int, input().split()))\n# write your code here', '[{"input":"6\n900 940 950 1100 1500 1800\n910 1200 1120 1130 1900 2000","expected_output":"3"}]', '[{"input":"6\n900 940 950 1100 1500 1800\n910 1200 1120 1130 1900 2000","expected_output":"3"}]', '[{"input":"3\n100 200 300\n150 250 350","expected_output":"1"}]', 'n, arrivals, departures', 'Minimum platforms', '1 <= n <= 100000', '["sorting","greedy"]', '["python","java","cpp","javascript"]', 15),
('Climbing Stairs', 'Print the number of distinct ways to climb n stairs taking 1 or 2 steps at a time.', 'medium', 'n = int(input())\n# write your code here', '[{"input":"4","expected_output":"5"},{"input":"1","expected_output":"1"}]', '[{"input":"4","expected_output":"5"}]', '[{"input":"10","expected_output":"89"}]', 'Integer n', 'Number of ways', '1 <= n <= 45', '["dynamic-programming"]', '["python","java","cpp","javascript"]', 15),
('Coin Change Ways', 'Given coin denominations and an amount, print the number of ways to make the amount.', 'medium', 'n, amount = map(int, input().split())\ncoins = list(map(int, input().split()))\n# write your code here', '[{"input":"3 4\n1 2 3","expected_output":"4"},{"input":"2 5\n2 5","expected_output":"1"}]', '[{"input":"3 4\n1 2 3","expected_output":"4"}]', '[{"input":"4 10\n2 5 3 6","expected_output":"5"}]', 'n amount and coins', 'Number of combinations', '1 <= amount <= 5000', '["dynamic-programming"]', '["python","java","cpp","javascript"]', 15),
('Kth Largest Element', 'Print the kth largest element in the array.', 'medium', 'n, k = map(int, input().split())\narr = list(map(int, input().split()))\n# write your code here', '[{"input":"6 2\n3 2 1 5 6 4","expected_output":"5"},{"input":"5 1\n7 4 6 3 9","expected_output":"9"}]', '[{"input":"6 2\n3 2 1 5 6 4","expected_output":"5"}]', '[{"input":"4 4\n10 20 30 40","expected_output":"10"}]', 'n k and array', 'kth largest value', '1 <= k <= n <= 100000', '["heap","sorting"]', '["python","java","cpp","javascript"]', 15),
('Graph BFS Distance', 'Given an unweighted undirected graph and source, print shortest distances from source or -1.', 'hard', 'n, m = map(int, input().split())\nedges = [tuple(map(int, input().split())) for _ in range(m)]\ns = int(input())\n# write your code here', '[{"input":"4 3\n0 1\n1 2\n2 3\n0","expected_output":"0 1 2 3"}]', '[{"input":"4 3\n0 1\n1 2\n2 3\n0","expected_output":"0 1 2 3"}]', '[{"input":"5 2\n0 1\n3 4\n0","expected_output":"0 1 -1 -1 -1"}]', 'n m, edges, source', 'Distances space-separated', '1 <= n <= 100000', '["graph","bfs"]', '["python","java","cpp","javascript"]', 20),
('Detect Cycle Directed', 'Given a directed graph, print YES if it contains a cycle, otherwise NO.', 'hard', 'n, m = map(int, input().split())\nedges = [tuple(map(int, input().split())) for _ in range(m)]\n# write your code here', '[{"input":"3 3\n0 1\n1 2\n2 0","expected_output":"YES"},{"input":"3 2\n0 1\n1 2","expected_output":"NO"}]', '[{"input":"3 3\n0 1\n1 2\n2 0","expected_output":"YES"}]', '[{"input":"4 4\n0 1\n1 2\n2 3\n1 3","expected_output":"NO"}]', 'n m and directed edges', 'YES or NO', '1 <= n <= 100000', '["graph","dfs"]', '["python","java","cpp","javascript"]', 20),
('Longest Increasing Subsequence', 'Print the length of the longest strictly increasing subsequence.', 'hard', 'n = int(input())\narr = list(map(int, input().split()))\n# write your code here', '[{"input":"6\n10 9 2 5 3 7","expected_output":"3"},{"input":"5\n1 2 3 4 5","expected_output":"5"}]', '[{"input":"6\n10 9 2 5 3 7","expected_output":"3"}]', '[{"input":"8\n0 8 4 12 2 10 6 14","expected_output":"4"}]', 'n and array', 'LIS length', '1 <= n <= 100000', '["dynamic-programming","binary-search"]', '["python","java","cpp","javascript"]', 20),
('LRU Cache Simulation', 'Simulate an LRU cache. For each GET key, print the value or -1. PUT key value updates the cache.', 'hard', 'capacity, q = map(int, input().split())\n# next q lines: GET key or PUT key value\n# write your code here', '[{"input":"2 5\nPUT 1 10\nPUT 2 20\nGET 1\nPUT 3 30\nGET 2","expected_output":"10\n-1"}]', '[{"input":"2 5\nPUT 1 10\nPUT 2 20\nGET 1\nPUT 3 30\nGET 2","expected_output":"10\n-1"}]', '[{"input":"1 4\nPUT 5 50\nGET 5\nPUT 6 60\nGET 5","expected_output":"50\n-1"}]', 'capacity q and operations', 'GET outputs per line', '1 <= q <= 100000', '["hashing","linked-list","design"]', '["python","java","cpp","javascript"]', 20),
('Median of Two Sorted Arrays', 'Given two sorted arrays, print their median. Use .5 for halves if needed.', 'hard', 'n, m = map(int, input().split())\na = list(map(int, input().split()))\nb = list(map(int, input().split()))\n# write your code here', '[{"input":"2 1\n1 3\n2","expected_output":"2"},{"input":"2 2\n1 2\n3 4","expected_output":"2.5"}]', '[{"input":"2 1\n1 3\n2","expected_output":"2"}]', '[{"input":"0 3\n\n2 3 4","expected_output":"3"}]', 'n m and sorted arrays', 'Median', '0 <= n,m <= 100000', '["array","binary-search"]', '["python","java","cpp","javascript"]', 20)
ON CONFLICT (title) DO NOTHING;

-- Seed default super admin account (password: admin123)
INSERT INTO users (name, email, password_hash, role)
VALUES (
  'Super Admin',
  'admin@intellihire.com',
  '$2b$10$HbZw6q4fwUv/QEupu7KiFupJc1Com7X4WRAqJ6rjjA.YDQoQ4Snne', -- admin123 (bcrypt)
  'admin'
) ON CONFLICT (email) DO NOTHING;
