ALTER TABLE "users" ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE "exams" ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE "questions" ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
